### ISSUE TITLE
Failing to launch app react native [android] after installing library

### ISSUE THREAD

**Issue by tendaimaswaya** [pusher/pusher-websocket-react-native#35] opened 2022-09-20 22:16 UTC
**Problem:**
Failing to launch app after installing react native sdk for pusher

**Platforms:**
React Native: **0.70.1**
@pusher/pusher-websocket-react-native: **"^1.0.2"**

N.B: Only tried running Android

**Steps to reproduce:**
1. Run `yarn add @pusher/pusher-websocket-react-native` as per documentation to install the pusher library.
2. Run `yarn android` to launch app on device

**Expectation:**
App should launch

**Actual:**
App fails to launch with **error**:

**On VSCode Terminal:**

```
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':pusher_pusher-websocket-react-native:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================
```

**On Android Studio:**

```
	•	failed
	•	:pusher_pusher-websocket-react-native:compileDebugKotlin
	•	/Users/me/.gradle/caches/transforms-3/2cfe106a332c6a6f2245988cf5920bcb/transformed/jetified-kotlin-stdlib-common-1.6.10.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
	•	/Users/me/.gradle/caches/transforms-3/66d59e3c479db3ee1833aa8684ea1547/transformed/jetified-react-native-0.70.1-debug-api.jar!/META-INF/ReactAndroid_debug.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
	•	/Users/me/.gradle/caches/transforms-3/8fa201288e2c6500b9e1af2f8ed9c77c/transformed/jetified-kotlin-stdlib-jdk7-1.6.10.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
	•	/Users/me/.gradle/caches/transforms-3/b6d16718b0badf943a01bd505b26edc1/transformed/jetified-kotlin-stdlib-jdk8-1.6.10.jar!/META-INF/kotlin-stdlib-jdk8.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
	•	/Users/me/.gradle/caches/transforms-3/d3fc290c9b603f2d0c573f31aa64957d/transformed/jetified-kotlin-stdlib-1.6.10.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.
	•	PusherWebsocketReactNativeModule.kt
	•	PusherWebsocketReactNativePackage.kt

```

The error on Android Studio explains more with the Kotlin version. I however noticed `kotlin_version` is specifed in the pusher library and did not think it a good idea to temper with this, neither did i think it a good idea to explicitly specify `kotlin_version` in any section of the android

**Comment by sin2** [comment] 2022-09-28 17:14
I was able to resolve this issue in my project by defining kotlinVersion and adding the following line to by android/build.gradle
`classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"`

**Comment by benjamin-tang-pusher** [comment] 2022-10-04 15:33
As a temporary workaround I added `kotlinVersion = '1.6.10'` (or 1.7.20) to the project level bulid.gradle. You are right that we shouldn't have to do this manually.

In Android Studio I'm getting:
`jetified-kotlin-stdlib-common-1.6.10.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.1.15.`

I'm not sure where the 1.1.15 is coming from. I will ask the team.

**Comment by benjamin-tang-pusher** [comment] 2023-01-23 19:01
Me and an engineer were investigating and somehow we can't reproduce this anymore (it might have been a change with RN 0.71 or our lib which is now 1.2). Therefore I will close this issue, since no one else has reported it since.

**Closed by benjamin-tang-pusher** 2023-01-23 19:01 UTC
