### ISSUE TITLE
The on Event and onAuthorizer only gets called one time in useEffect

### ISSUE THREAD

**Issue by TonyStinson1** [pusher/pusher-websocket-react-native#103] opened 2023-06-30 14:41 UTC
The  issue is with the connect function below 
`
const connect = async () => {
    try {
      await AsyncStorage.multiSet([
        ['APIKEY', apiKey],
        ['CLUSTER', cluster],
        ['CHANNEL', channelName],
      ]);

      await pusher.init({
        apiKey,
        cluster,
        onAuthorizer,
        onConnectionStateChange,
        onError,
        onEvent,
        onSubscriptionSucceeded,
        onSubscriptionError,
        onSubscriptionCount,
        onDecryptionFailure,
        onMemberAdded,
        onMemberRemoved,
        useTLS: true
      });
      console.log("Channel name is ", channelName);
      await pusher.connect();
      await pusher.subscribe({ channelName });
    } catch (e) {
      console.log('ERROR: ' + e);
    }
  };
`

This particular function gets called in useEffect but once we navigate to some other screens and come back the onAuthorizer and onEvent doesn't gets called.

Hence the catching of event also stops.

But the other functiions form the above part like onConnectionStateChange, onError, keeps on getting called and shows the connection is still intact

**Comment by Shasikhan** [comment] 2023-07-05 16:13
Same here. Any solution you found yet?

**Comment by mohamedanwermohamed** [comment] 2023-07-12 11:27
the correct behaviour you will connect to pusher on time only when lunch the app and subscribe/unsubscribe in any screen you want .. 

if you try connect pusher more than one time you will get error

**Comment by benjamin-tang-pusher** [comment] 2023-10-19 21:00
I had a look at this, and I cannot reproduce this: I'm running the same example code as you plus I'm using createNativeStackNavigator() and <NavigationContainer> to push onto a second screen. Then I pop back to the original screen, and throughout this I can receive events both on the second screen and after returning to the home screen.

I did notice a bizarre issue with disconnecting: after reconnecting again the library does not let you subscribe to the same channel as before. I think there's and issue with the library state not cleaning up properly after calling disconnect, and thinking the channel is still subscribed. But its not, and the channel won't be listened to. This will be a separate issue I will raise internally.

**Comment by Shasikhan** [comment] 2023-10-31 06:54
This issue is fixed in latest version. When unmounting component, use below code

`await pusher.reset();`

**Closed** 2024-03-26 16:27 UTC
