### ISSUE TITLE
Pong reply not recieved

### ISSUE THREAD

**Issue by Bayramito** [pusher/pusher-websocket-react-native#89] opened 2023-04-18 11:13 UTC
![Ekran Resmi 2023-04-18 14 13 20](https://user-images.githubusercontent.com/44513402/232760225-23ab27d1-09c4-48a9-a32f-978549794ecc.png)

**Comment by benw-pusher** [comment] 2023-04-18 11:33
Pong reply not received is a normal error that would be expected when the client has lost communication with the server. However, we wouldn't expect a crash to be triggered by this, although in this case the crash is a duplicate of https://github.com/pusher/pusher-websocket-react-native/issues/85. I'll close this new ticket as a duplicate.

**Closed by benw-pusher** 2023-04-18 11:33 UTC
