### ISSUE TITLE
App Crashing when logging event on IOS

### ISSUE THREAD

**Issue by YosefOberlander** [pusher/pusher-websocket-react-native#29] opened 2022-08-28 15:56 UTC
React Native Version: 0.69.2
pusher-websocket-react-native version: 1.0.2.
Bare react-native project

When logging `event.data` to the console the app crashes. If i log `pusherEvent` It logs the message successfully, but trying to access `pusherEvent.data` crashes the app. The app also crashes if you refresh the and receive an event. On the first load of the app everything works.

`await pusher.subscribe(
            {
                channelName: "my-channel",
                onEvent: (event) => {
                    console.log(`Event received`);
                    console.log(event.data);
                }
            }
        );`

error: 
`terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Error when sending event: onEvent with body: {
    channelName = "my-channel";
    data = "{\"message\":{\"id\":111,\"chat_room_id\":3,\"user_id\":1,\"parent_id\":null,\"has_attached_media\":null,\"job_attachment_id\":null,\"created_at\":\"2022-08-28T17:16:21.000000Z\",\"updated_at\":\"2022-08-28T17:16:21.000000Z\",\"message\":\"R\",\"user\":{\"id\":1,\"name\":\"Administrator\",\"email\":\"administrator@app.com\",\"email_verified_at\":null,\"created_at\":\"2022-08-07T03:14:11.000000Z\",\"updated_at\":\"2022-08-26T20:26:48.000000Z\",\"needs_approval\":0,\"needs_approval_by\":null,\"notify_poe_image\":0,\"avatar\":\"https:\\/\\/www.gravatar.com\\/avatar\\/09a7ea0fc3c71cd27275ccf23ddf2670?d=wavatar\"},\"room\":{\"id\":3,\"job_id\":2,\"room_title\":\"Test1\",\"user_id\":1,\"created_at\":\"1 day ago\",\"updated_at\":\"2022-08-26T21:25:45.000000Z\"}}}";
    eventName = "App\\Events\\MyEvent";
    userId = "<null>";
}. RCTCallableJSModules is not set. This is probably because you've explicitly synthesized the RCTCallableJSModules in PusherWebsocketReactNative, even though it's inherited from RCTEventEmitter.'
CoreSimulator 802.6.1 - Device: iPhone 13 Pro (86ABA976-9834-4648-A06C-A3427A4D2DD6) - Runtime: iOS 15.5 (19F70) - DeviceType: iPhone 13 Pro`

**Comment by YosefOberlander** [comment] 2022-08-28 17:07
I think it has something todo with `RCTCallableJSModules is not set. This is probably because you've explicitly synthesized the RCTCallableJSModules in PusherWebsocketReactNative, even though it's inherited from RCTEventEmitter.'`

**Comment by nguyenngockha2904** [comment] 2022-09-07 17:06
@YosefOberlander have you resolved this issue?
have you run command "pod install" success? please help me this issue (https://github.com/pusher/pusher-websocket-react-native/issues/31)

**Comment by YosefOberlander** [comment] 2022-09-07 17:14
I couldn't find a solution so I ended up going with a different package. Not sure why changing your platform to 13 didn't work): it worked for me

**Comment by YosefOberlander** [comment] 2022-09-07 17:16
In the screenshot you provided, your platform was still at 12 not 13

**Comment by nguyenngockha2904** [comment] 2022-09-07 17:25
I change to 13 already, but it still not work
<img width="1379" alt="188935954-681e2f13-5af0-4e2a-8e74-d473e8a024ef" src="https://user-images.githubusercontent.com/55082300/188941182-46c8ad1a-ae65-47e3-bb9f-f0a53e0a065e.png">

**Comment by nguyenngockha2904** [comment] 2022-09-07 17:31
maybe it's because react native version?
I use React Native Version: 0.68.2 but you're 0.69.2

**Comment by nguyenngockha2904** [comment] 2022-09-07 17:35
in android, my pusher code work fine, maybe can have your issue
<img width="601" alt="image" src="https://user-images.githubusercontent.com/55082300/188942635-c5d6800b-5b30-4824-8626-353dbd8ea32d.png">

**Comment by benjamin-tang-pusher** [comment] 2022-10-05 16:14
Please stay on topic.

Mine is printing to the (Metro) console ok:
```
  const onEvent = (event: any) => {
    console.log(`onEvent: ${event}`);
    console.log(event.data)
  };
```
I triggered from my Pusher dashboard debug console:
`API message | Channel: some-channel, Event: my-event | 16:11:51 |   | aaaaaaa`

Then I have in my Metro console:
```
 LOG  onEvent: { channelName: some-channel, eventName: my-event, data: aaaaaaa, userId: null }
 LOG  aaaaaaa
```
I think part of the issue might be your '\' escape character in your event.data. Can you test triggering just a string from your debug console?

**Comment by benjamin-tang-pusher** [comment] 2022-10-17 10:46
I will close this as I couldn't reproduce.

**Closed by benjamin-tang-pusher** 2022-10-17 10:46 UTC
